// NexusCore Day 5 — eBPF Userspace Loader & Histogram Aggregator
// Uses cilium/ebpf (pure Go, no CGo dependency at runtime)
//
// Responsibilities:
//  1. Load & pin the BPF object (CO-RE relocations handled by libbpf-go)
//  2. Attach kprobes to target functions
//  3. Register target PIDs in the filter map
//  4. Poll ring buffer for raw events → JSON stream
//  5. Aggregate PERCPU histograms every N seconds → stdout metrics

package main

import (
	"encoding/json"
	"fmt"
	"log"
	"math"
	"os"
	"os/signal"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang-16 -cflags "-O2 -g -Wall -DBPF_NO_PRESERVE_ACCESS_INDEX" nexuscore ./src/nexuscore_probe.bpf.c -- -I/usr/include/$(uname -m)-linux-gnu

const (
	StackSurreal  = 0
	StackPolyglot = 1
	OpVFSRead     = 0
	OpVFSWrite    = 1
	OpTCPSend     = 2
)

type RawEvent struct {
	PID       uint32  `json:"pid"`
	Stack     uint8   `json:"stack"`    // 0=surreal, 1=polyglot
	Op        uint8   `json:"op"`       // 0=vfs_read, 1=vfs_write, 2=tcp_send
	Pad       uint16  `json:"-"`
	LatencyNS uint64  `json:"latency_ns"`
	Bytes     uint64  `json:"bytes"`
}

type HistogramReport struct {
	Timestamp  time.Time         `json:"ts"`
	Stack      string            `json:"stack"`
	Operation  string            `json:"op"`
	P50NS      uint64            `json:"p50_ns"`
	P99NS      uint64            `json:"p99_ns"`
	P999NS     uint64            `json:"p999_ns"`
	TotalCount uint64            `json:"total_count"`
	Buckets    map[uint32]uint64 `json:"buckets"`
}

func main() {
	// Remove memlock limit — required for BPF maps
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatalf("removing memlock: %v", err)
	}

	// Parse target PIDs from args: ./loader --surreal=<pid> --polyglot=<pid1>,<pid2>
	surrealPIDs, polyglotPIDs := parsePIDArgs(os.Args[1:])
	if len(surrealPIDs) == 0 && len(polyglotPIDs) == 0 {
		log.Fatal("Usage: ./loader --surreal=<pid> --polyglot=<pid1,pid2,...>")
	}

	// Load pre-compiled BPF object (generated by bpf2go)
	objs := nexuscoreObjects{}
	if err := loadNexuscoreObjects(&objs, nil); err != nil {
		log.Fatalf("loading BPF objects: %v", err)
	}
	defer objs.Close()

	// Attach kprobes
	kprobes := []struct {
		symbol string
		prog   *ebpf.Program
	}{
		{"vfs_read", objs.ProbeVfsReadEnter},
		{"vfs_read", objs.ProbeVfsReadExit},
		{"tcp_sendmsg", objs.ProbeTcpSendmsgEnter},
		{"tcp_sendmsg", objs.ProbeTcpSendmsgExit},
	}

	var links []link.Link
	for _, kp := range kprobes {
		lnk, err := link.Kprobe(kp.symbol, kp.prog, nil)
		if err != nil {
			log.Fatalf("attaching kprobe %s: %v", kp.symbol, err)
		}
		links = append(links, lnk)
	}
	defer func() {
		for _, l := range links { l.Close() }
	}()

	// Populate PID filter map
	for _, pid := range surrealPIDs {
		stackType := uint8(StackSurreal)
		if err := objs.TargetPids.Put(uint32(pid), stackType); err != nil {
			log.Printf("warn: could not add surreal PID %d: %v", pid, err)
		}
	}
	for _, pid := range polyglotPIDs {
		stackType := uint8(StackPolyglot)
		if err := objs.TargetPids.Put(uint32(pid), stackType); err != nil {
			log.Printf("warn: could not add polyglot PID %d: %v", pid, err)
		}
	}

	log.Printf("NexusCore eBPF probes active. Surreal PIDs: %v, Polyglot PIDs: %v", surrealPIDs, polyglotPIDs)

	// Start ring buffer reader
	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		log.Fatalf("opening ring buffer: %v", err)
	}
	defer rd.Close()

	go readEvents(rd)

	// Histogram reporter goroutine — every 5 seconds
	ticker := time.NewTicker(5 * time.Second)
	go func() {
		for range ticker.C {
			reportHistogram("surrealdb", "vfs_read", objs.HistSurrealRead)
			reportHistogram("polyglot", "vfs_read", objs.HistPolyglotRead)
			reportHistogram("combined", "tcp_sendmsg", objs.HistTcpSend)
		}
	}()

	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)
	<-sig
	log.Println("Shutting down NexusCore eBPF loader.")
}

func readEvents(rd *ringbuf.Reader) {
	enc := json.NewEncoder(os.Stdout)
	var record ringbuf.Record
	for {
		if err := rd.ReadInto(&record); err != nil {
			return
		}
		if len(record.RawSample) < 24 {
			continue
		}
		e := parseEvent(record.RawSample)
		_ = enc.Encode(e)
	}
}

func parseEvent(b []byte) RawEvent {
	return RawEvent{
		PID:       uint32(b[0]) | uint32(b[1])<<8 | uint32(b[2])<<16 | uint32(b[3])<<24,
		Stack:     b[4],
		Op:        b[5],
		LatencyNS: uint64(b[8]) | uint64(b[9])<<8 | uint64(b[10])<<16 | uint64(b[11])<<24 |
			uint64(b[12])<<32 | uint64(b[13])<<40 | uint64(b[14])<<48 | uint64(b[15])<<56,
		Bytes: uint64(b[16]) | uint64(b[17])<<8 | uint64(b[18])<<16 | uint64(b[19])<<24 |
			uint64(b[20])<<32 | uint64(b[21])<<40 | uint64(b[22])<<48 | uint64(b[23])<<56,
	}
}

func reportHistogram(stack, op string, m *ebpf.Map) {
	// PERCPU_ARRAY: value is []uint64, one per CPU
	var perCPUValues [][]uint64
	key := uint32(0)
	// Sum across all CPUs for each bucket
	combined := make(map[uint32]uint64)
	for slot := uint32(0); slot < 64; slot++ {
		key = slot
		if err := m.Lookup(key, &perCPUValues); err != nil {
			break
		}
		var sum uint64
		for _, cpuVal := range perCPUValues {
			if len(cpuVal) > 0 {
				sum += cpuVal[0]
			}
		}
		if sum > 0 {
			combined[slot] = sum
		}
	}
	if len(combined) == 0 {
		return
	}

	report := HistogramReport{
		Timestamp:  time.Now().UTC(),
		Stack:      stack,
		Operation:  op,
		Buckets:    combined,
	}
	report.P50NS, report.P99NS, report.P999NS, report.TotalCount = computePercentiles(combined)

	data, _ := json.MarshalIndent(report, "", "  ")
	fmt.Printf("--- HISTOGRAM [%s/%s] ---\n%s\n\n", stack, op, data)
}

// computePercentiles extracts p50/p99/p999 from log2 histogram
func computePercentiles(buckets map[uint32]uint64) (p50, p99, p999, total uint64) {
	var cum uint64
	for _, v := range buckets {
		total += v
	}
	if total == 0 {
		return
	}

	targets := [3]float64{0.50, 0.99, 0.999}
	results := [3]uint64{}
	idx := 0

	for slot := uint32(0); slot < 64 && idx < 3; slot++ {
		cum += buckets[slot]
		for idx < 3 && float64(cum)/float64(total) >= targets[idx] {
			// Midpoint of bucket [2^slot, 2^(slot+1))
			results[idx] = uint64(math.Pow(2, float64(slot)+0.5))
			idx++
		}
	}
	return results[0], results[1], results[2], total
}

func parsePIDArgs(args []string) (surreal, polyglot []int) {
	for _, arg := range args {
		if strings.HasPrefix(arg, "--surreal=") {
			surreal = parsePIDs(strings.TrimPrefix(arg, "--surreal="))
		} else if strings.HasPrefix(arg, "--polyglot=") {
			polyglot = parsePIDs(strings.TrimPrefix(arg, "--polyglot="))
		}
	}
	return
}

func parsePIDs(s string) []int {
	var out []int
	for _, part := range strings.Split(s, ",") {
		if n, err := strconv.Atoi(strings.TrimSpace(part)); err == nil {
			out = append(out, n)
		}
	}
	return out
}
