// SurrealDB adapter — host-side WIT interface implementation
// In full production: generated by wit-bindgen from surreal-adapter.wit
// Here: hand-written to show exact mechanics without code-gen magic

use crate::pool::ConnectionPool;
use std::sync::Arc;
use surrealdb::sql;

pub struct SurrealAdapterHost {
    pool: Arc<ConnectionPool>,
}

impl SurrealAdapterHost {
    pub fn new(pool: Arc<ConnectionPool>) -> Self { Self { pool } }

    /// Execute SurrealQL, return raw CBOR bytes.
    /// This is the hot path — zero JSON roundtrip.
    pub async fn exec(&self, tenant_id: &str, ns: &str, db: &str, surql: &str)
        -> anyhow::Result<Vec<u8>>
    {
        let conn = self.pool.get().await?;
        let start = std::time::Instant::now();

        // Use SurrealDB's CBOR serialization directly
        let mut response = conn.query(surql).await
            .map_err(|e| anyhow::anyhow!("query error: {}", e))?;

        let value = response.take(0usize).unwrap_or_else(|_| {
            surrealdb::Value::from_inner(sql::Value::None)
        });

        // Serialize to CBOR — Wasm component receives raw bytes
        let mut buf = Vec::with_capacity(512);
        ciborium::into_writer(&value, &mut buf)
            .map_err(|e| anyhow::anyhow!("cbor error: {}", e))?;

        let latency = start.elapsed().as_secs_f64();
        crate::metrics::record_query(tenant_id, "exec", latency, true);

        tracing::debug!("tenant={} op=exec latency={:.3}ms bytes={}", 
            tenant_id, latency * 1000.0, buf.len());

        Ok(buf)
    }

    /// RELATE src -> edge -> tgt — direct graph edge insertion.
    /// Bypasses the relational planner entirely.
    pub async fn relate(
        &self, tenant_id: &str,
        src: &str, edge: &str, tgt: &str,
        data: &[u8]
    ) -> anyhow::Result<Vec<u8>> {
        let conn = self.pool.get().await?;

        // Deserialize CBOR data payload from Wasm component
        let data_val = if data.is_empty() {
            surrealdb::Value::from_inner(sql::Value::Object(Default::default()))
        } else {
            let inner: sql::Value = ciborium::from_reader(data)
                .map_err(|e| anyhow::anyhow!("cbor decode: {}", e))?;
            surrealdb::Value::from_inner(inner)
        };

        let surql = format!("RELATE {}->{}->{}  CONTENT $data;", src, edge, tgt);
        let mut resp = conn.query(surql)
            .bind(("data", data_val))
            .await?;

        let result = resp.take(0usize).unwrap_or_else(|_| {
            surrealdb::Value::from_inner(sql::Value::None)
        });

        let mut buf = Vec::with_capacity(128);
        ciborium::into_writer(&result, &mut buf)?;
        Ok(buf)
    }
}
