//! NexusCore Day 35 — Host Orchestrator
//!
//! Manages N concurrent ReAct agent instances, each backed by a separate
//! Wasmtime Store (separate linear memory, separate fuel).
//! Uses FuturesUnordered for cooperative async scheduling — no OS thread per agent.

use anyhow::{anyhow, Context, Result};
use clap::Parser;
use futures::stream::{FuturesUnordered, StreamExt};
use serde::Serialize;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Instant;
use tokio::sync::{RwLock, Semaphore};
use wasmtime::component::{Component, Linker, ResourceTable};
use wasmtime::{Config, Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiView};
use wasmtime_wasi_http::{WasiHttpCtx, WasiHttpView};

use axum::extract::State;
use axum::http::Method;
use tower_http::cors::{Any, CorsLayer};

#[derive(Parser)]
#[command(name = "nexuscore", about = "NexusCore ReAct Agent Host")]
struct Cli {
    #[arg(short, long, default_value = "component/nexuscore_agent.wasm")]
    wasm: String,

    #[arg(short, long, default_value = "What is the latest Rust edition and what major features does it include?")]
    query: String,

    #[arg(short = 'n', long, default_value_t = 1)]
    concurrency: usize,

    #[arg(long, default_value = "https://api.anthropic.com/v1/messages")]
    llm_endpoint: String,

    #[arg(long, default_value = "http://localhost:8765")]
    search_endpoint: String,

    #[arg(long, env = "ANTHROPIC_API_KEY", default_value = "")]
    api_key: String,

    #[arg(long, default_value_t = 10)]
    max_steps: usize,

    #[arg(long, default_value_t = 8080)]
    metrics_port: u16,

    /// After each viz update, write JSON here so the static dashboard (port 9090) can read
    /// `./last-viz.json` when the host is not running (demo exits when the agent finishes).
    #[arg(long, default_value = "visualizer/last-viz.json")]
    viz_snapshot: PathBuf,
}

// ── WASI State ────────────────────────────────────────────────────────────────
struct AgentState {
    wasi: WasiCtx,
    http: WasiHttpCtx,
    table: ResourceTable,
}

impl WasiView for AgentState {
    fn ctx(&mut self) -> &mut WasiCtx { &mut self.wasi }
    fn table(&mut self) -> &mut ResourceTable { &mut self.table }
}
impl WasiHttpView for AgentState {
    fn ctx(&mut self) -> &mut WasiHttpCtx { &mut self.http }
    fn table(&mut self) -> &mut ResourceTable { &mut self.table }
}

// ── Component bindings (generated by wit-bindgen) ────────────────────────────
// In a real build this would be: wasmtime::component::bindgen!({...})
// We use a manual interface here to avoid requiring a pre-built Wasm binary
// in the setup script.
wasmtime::component::bindgen!({
    path: "../agent-component/wit",
    world: "agent-world",
    async: true,
});

// ── Metrics ──────────────────────────────────────────────────────────────────
use prometheus::{Histogram, HistogramOpts, Registry};
use std::sync::OnceLock;

static METRICS: OnceLock<Arc<AgentMetrics>> = OnceLock::new();

struct AgentMetrics {
    registry: Registry,
    step_latency: Histogram,
    total_latency: Histogram,
}

impl AgentMetrics {
    fn new() -> Result<Self> {
        let registry = Registry::new();
        let step_latency = Histogram::with_opts(
            HistogramOpts::new("nexuscore_step_latency_seconds", "Per-step latency")
                .buckets(vec![0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0, 10.0]),
        )?;
        let total_latency = Histogram::with_opts(
            HistogramOpts::new("nexuscore_agent_latency_seconds", "Full agent run latency")
                .buckets(vec![1.0, 2.0, 5.0, 10.0, 30.0, 60.0]),
        )?;
        registry.register(Box::new(step_latency.clone()))?;
        registry.register(Box::new(total_latency.clone()))?;
        Ok(AgentMetrics { registry, step_latency, total_latency })
    }
}

// ── Dashboard JSON (visualizer polls this; single-flight snapshot for demos) ─
#[derive(Clone, Serialize, Default)]
struct VizStepPayload {
    thought: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    action: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    action_input: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    observation: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    final_answer: Option<String>,
    step_index: u32,
    latency_ms: f64,
}

#[derive(Clone, Serialize, Default)]
struct VizState {
    query: String,
    running: bool,
    agent_id: usize,
    steps: Vec<VizStepPayload>,
    total_elapsed_s: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    error: Option<String>,
}

async fn persist_viz_snapshot(path: &std::path::Path, viz: &Arc<RwLock<VizState>>) {
    let state = viz.read().await.clone();
    let snap = match serde_json::to_vec_pretty(&state) {
        Ok(b) => b,
        Err(e) => {
            tracing::warn!("viz snapshot serialize failed: {e}");
            return;
        }
    };
    if let Some(parent) = path.parent() {
        if let Err(e) = tokio::fs::create_dir_all(parent).await {
            tracing::warn!(?e, "viz snapshot mkdir failed");
            return;
        }
    }
    if let Err(e) = tokio::fs::write(path, snap).await {
        tracing::warn!(?e, ?path, "viz snapshot write failed");
    }
}

// ── Agent Runner ──────────────────────────────────────────────────────────────
async fn run_agent(
    engine: Arc<Engine>,
    component: Arc<Component>,
    agent_id: usize,
    query: String,
    llm_endpoint: String,
    search_endpoint: String,
    api_key: String,
    max_steps: usize,
    viz: Arc<RwLock<VizState>>,
    viz_snapshot: PathBuf,
) -> Result<String> {
    let metrics = METRICS.get().expect("metrics not initialized");
    let run_start = Instant::now();

    {
        let mut v = viz.write().await;
        v.query = query.clone();
        v.running = true;
        v.agent_id = agent_id;
        v.steps.clear();
        v.error = None;
        v.total_elapsed_s = 0.0;
    }
    persist_viz_snapshot(&viz_snapshot, &viz).await;

    let run_result = async {
        // Each agent gets its own Store — isolated linear memory
        let wasi = WasiCtxBuilder::new()
            .inherit_stdio()
            .build();
        let state = AgentState { wasi, http: WasiHttpCtx::new(), table: ResourceTable::new() };
        let mut store = Store::new(&engine, state);
        store.set_fuel(1_000_000_000).ok(); // 1B Wasm instructions per agent

        let mut linker = Linker::new(&engine);
        wasmtime_wasi::add_to_linker_async(&mut linker)?;
        wasmtime_wasi_http::proxy::add_only_http_to_linker(&mut linker)?;

        let (agent_world, _) = AgentWorld::instantiate_async(&mut store, &component, &linker).await?;
        let react = agent_world.nexuscore_agent_react_agent();

        let mut history = Vec::new();
        let mut final_answer = None;

        for step in 0..max_steps {
            let step_start = Instant::now();

            println!("[agent-{agent_id}] step {step}: thinking...");

            let result = react
                .call_run_step(
                    &mut store,
                    &query,
                    &history,
                    &llm_endpoint,
                    &search_endpoint,
                    &api_key,
                )
                .await
                .map_err(|e| anyhow!("Wasm call failed: {e}"))?
                .map_err(|e| anyhow!("Agent error: {e}"))?;

            let step_elapsed = step_start.elapsed().as_secs_f64();
            metrics.step_latency.observe(step_elapsed);

            {
                let mut v = viz.write().await;
                v.steps.push(VizStepPayload {
                    thought: result.thought.clone(),
                    action: result.action.clone(),
                    action_input: result.action_input.clone(),
                    observation: result.observation.clone(),
                    final_answer: result.final_answer.clone(),
                    step_index: result.step_index,
                    latency_ms: step_elapsed * 1000.0,
                });
                v.total_elapsed_s = run_start.elapsed().as_secs_f64();
            }
            persist_viz_snapshot(&viz_snapshot, &viz).await;

            println!("[agent-{agent_id}] Thought: {}", result.thought);
            if let Some(ref action) = result.action {
                let input = result.action_input.as_deref().unwrap_or("");
                println!("[agent-{agent_id}] Action: {action}[{input}]");
            }
            if let Some(ref obs) = result.observation {
                println!("[agent-{agent_id}] Observation: {obs}");
            }

            if let Some(ref ans) = result.final_answer {
                println!("[agent-{agent_id}] ✓ Final Answer: {ans}");
                final_answer = Some(ans.clone());
                history.push(result);

                // Reset arena between runs (not steps — arena persists across steps for history)
                react.call_reset_arena(&mut store).await?;
                break;
            }

            history.push(result);
        }

        let total_elapsed = run_start.elapsed().as_secs_f64();
        metrics.total_latency.observe(total_elapsed);
        println!(
            "[agent-{agent_id}] completed in {total_elapsed:.2}s over {} steps",
            history.len()
        );

        final_answer.ok_or_else(|| anyhow!("Agent exhausted max_steps without final answer"))
    }
    .await;

    {
        let mut v = viz.write().await;
        v.running = false;
        v.total_elapsed_s = run_start.elapsed().as_secs_f64();
        if let Err(ref e) = run_result {
            v.error = Some(format!("{e:#}"));
        }
    }
    persist_viz_snapshot(&viz_snapshot, &viz).await;

    run_result
}

// ── Metrics HTTP Handler ───────────────────────────────────────────────────────
async fn metrics_handler(State(_): State<Arc<RwLock<VizState>>>) -> String {
    if let Some(m) = METRICS.get() {
        use prometheus::Encoder;
        let encoder = prometheus::TextEncoder::new();
        let mut buffer = Vec::new();
        encoder.encode(&m.registry.gather(), &mut buffer).unwrap_or(());
        String::from_utf8(buffer).unwrap_or_default()
    } else {
        "# metrics not ready\n".to_string()
    }
}

async fn viz_handler(State(viz): State<Arc<RwLock<VizState>>>) -> axum::Json<VizState> {
    axum::Json(viz.read().await.clone())
}

// ── Main ──────────────────────────────────────────────────────────────────────
#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();

    tracing_subscriber::fmt()
        .with_env_filter(std::env::var("RUST_LOG").unwrap_or_else(|_| "info".into()))
        .init();

    // Initialize metrics
    METRICS.set(Arc::new(AgentMetrics::new()?))
        .map_err(|_| anyhow!("metrics already initialized"))?;

    // Build Wasmtime engine with AOT caching
    let mut config = Config::new();
    config.async_support(true);
    config.cache_config_load_default().ok(); // Load ~/.wasmtime/cache or WASMTIME_CACHE_CONFIG
    config.wasm_component_model(true);

    let engine = Arc::new(Engine::new(&config)?);

    // Load and pre-compile component (AOT)
    let wasm_bytes = std::fs::read(&cli.wasm)
        .with_context(|| format!("Cannot read Wasm component: {}", cli.wasm))?;
    let component = Arc::new(
        Component::from_binary(&engine, &wasm_bytes)?
    );
    println!("✓ Component loaded and compiled: {}", cli.wasm);

    let viz = Arc::new(RwLock::new(VizState::default()));

    // Spawn metrics + dashboard API (visualizer polls /api/viz)
    let metrics_port = cli.metrics_port;
    let viz_server = viz.clone();
    tokio::spawn(async move {
        use axum::{routing::get, Router};
        let app = Router::new()
            .route("/metrics", get(metrics_handler))
            .route("/api/viz", get(viz_handler))
            .with_state(viz_server)
            .layer(
                CorsLayer::new()
                    .allow_origin(Any)
                    .allow_methods([Method::GET]),
            );
        let addr = format!("0.0.0.0:{metrics_port}");
        println!("✓ Prometheus metrics on http://{addr}/metrics");
        println!("✓ Dashboard API on http://{addr}/api/viz");
        let listener = tokio::net::TcpListener::bind(&addr).await.unwrap();
        axum::serve(listener, app).await.unwrap();
    });

    // Concurrency limiter
    let sem = Arc::new(Semaphore::new(cli.concurrency));
    let mut tasks = FuturesUnordered::new();

    for i in 0..cli.concurrency {
        let permit = sem.clone().acquire_owned().await?;
        let engine = engine.clone();
        let component = component.clone();
        let query = cli.query.clone();
        let llm = cli.llm_endpoint.clone();
        let search = cli.search_endpoint.clone();
        let key = cli.api_key.clone();
        let max_steps = cli.max_steps;
        let viz_run = viz.clone();
        let viz_snap = cli.viz_snapshot.clone();

        tasks.push(tokio::spawn(async move {
            let result = run_agent(
                engine,
                component,
                i,
                query,
                llm,
                search,
                key,
                max_steps,
                viz_run,
                viz_snap,
            )
            .await;
            drop(permit);
            result
        }));
    }

    let mut success = 0usize;
    let mut failure = 0usize;
    while let Some(result) = tasks.next().await {
        match result {
            Ok(Ok(_))  => success += 1,
            Ok(Err(e)) => { eprintln!("Agent error: {e}"); failure += 1; }
            Err(e)     => { eprintln!("Task panic: {e}"); failure += 1; }
        }
    }

    println!("\n── Summary ─────────────────────");
    println!("  Agents: {}", cli.concurrency);
    println!("  Success: {success}  Failure: {failure}");
    println!("─────────────────────────────────");
    Ok(())
}
