// NexusCore Wasm Guest Component — Day 1
// Compiled to wasm32-wasip2 (WASI 0.3 component model)
// This is the tenant isolation boundary.
//
// CRITICAL DESIGN: This component has NO knowledge of:
// - Which SurrealDB node it's talking to
// - How many other tenants exist
// - The host's connection pool size
// All of that is the host's concern. This component is "shared-nothing."

// In production, generated by wit-bindgen from surreal-adapter.wit
// wit_bindgen::generate!({
//     world: "surreal-guest",
//     path:  "../wit/surreal-adapter.wit",
// });

use serde::{Deserialize, Serialize};

/// Tenant request event — CBOR encoded by the host before calling `run`
#[derive(Debug, Deserialize)]
struct TenantEvent {
    tenant_id: String,
    operation: String,  // "select" | "relate" | "upsert" | "live"
    payload:   serde_json::Value,
}

/// Response — CBOR encoded, returned to host
#[derive(Debug, Serialize)]
struct TenantResponse {
    tenant_id: String,
    status:    String,
    data:      serde_json::Value,
    model:     String, // which SurrealDB model was used
}

/// Entry point called by the host for every tenant request.
/// 
/// Memory discipline: we receive a raw byte slice (host writes into our
/// linear memory via WIT list<u8> lowering). We own it. No copies.
/// We return a Vec<u8> (CBOR); the host reads it and frees it via
/// the canonical ABI's post-return cleanup.
#[no_mangle]
pub extern "C" fn run(ptr: *const u8, len: usize) -> u64 {
    // Safety: host guarantees valid CBOR in our linear memory
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };

    let response_bytes = match process_event(bytes) {
        Ok(b) => b,
        Err(e) => {
            let err_resp = TenantResponse {
                tenant_id: "unknown".into(),
                status:    "error".into(),
                data:      serde_json::Value::String(e),
                model:     "none".into(),
            };
            encode_cbor(&err_resp).unwrap_or_default()
        }
    };

    // Pack pointer + length into u64 for ABI return
    // Host's post-return will call component_free() on our allocator
    let result_ptr = response_bytes.as_ptr() as u64;
    let result_len = response_bytes.len() as u64;
    std::mem::forget(response_bytes); // Host owns it now
    (result_ptr << 32) | result_len
}

fn process_event(bytes: &[u8]) -> Result<Vec<u8>, String> {
    // Decode CBOR event
    let event: TenantEvent = ciborium::from_reader(bytes)
        .map_err(|e| format!("cbor decode: {}", e))?;

    // Choose the right SurrealDB semantic model based on operation type
    let (surql, model) = match event.operation.as_str() {
        "select" => {
            // Document / relational model
            let table = event.payload["table"].as_str().unwrap_or("user");
            let limit = event.payload["limit"].as_u64().unwrap_or(10);
            (format!("SELECT * FROM {} LIMIT {};", table, limit), "relational")
        }
        "relate" => {
            // Graph model — RELATE avoids JOINs for traversal
            let src  = event.payload["src"].as_str().unwrap_or("user:alice");
            let edge = event.payload["edge"].as_str().unwrap_or("accessed");
            let tgt  = event.payload["tgt"].as_str().unwrap_or("page:home");
            (format!("RELATE {}->{}->{}; SELECT ->{}->* FROM {};",
                src, edge, tgt, edge, src), "graph")
        }
        "fulltext" => {
            // Full-text search model — BM25 via SurrealDB analyzer
            let term = event.payload["term"].as_str().unwrap_or("");
            (format!("SELECT * FROM user WHERE email @@ '{}';", term), "fulltext")
        }
        "live" => {
            // CDC: LIVE SELECT — streaming change events
            ("LIVE SELECT * FROM user;".into(), "cdc")
        }
        op => return Err(format!("unknown operation: {}", op)),
    };

    // In production: call host via WIT `query::exec(surql)`
    // The WIT call writes the result directly into our linear memory.
    // For this scaffold: return the constructed SurrealQL for inspection.
    let resp = TenantResponse {
        tenant_id: event.tenant_id,
        status:    "ok".into(),
        data:      serde_json::json!({
            "surql": surql,
            "model": model,
            "note":  "In production: result is CBOR bytes from SurrealDB via WIT query::exec()"
        }),
        model: model.into(),
    };

    encode_cbor(&resp).map_err(|e| e.to_string())
}

fn encode_cbor<T: Serialize>(val: &T) -> Result<Vec<u8>, ciborium::ser::Error<std::io::Error>> {
    let mut buf = Vec::with_capacity(256);
    ciborium::into_writer(val, &mut buf)?;
    Ok(buf)
}

/// Called by host before tenant eviction.
/// Component MUST release all WIT resource handles here.
#[no_mangle]
pub extern "C" fn on_evict() {
    // In production: drop all query::QueryHandle resources
    // The WIT resource destructor will release the pool slot back to the host.
    // Here: no-op since we hold no persistent resources in this scaffold.
}
