// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod nexuscore {
        pub mod cdc {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod processor {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[derive(Clone)]
                pub struct CdcEvent {
                    pub tenant_id: u64,
                    pub table_hash: _rt::Vec<u8>,
                    pub payload: _rt::Vec<u8>,
                    pub ts_ns: u64,
                }
                impl ::core::fmt::Debug for CdcEvent {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("CdcEvent")
                            .field("tenant-id", &self.tenant_id)
                            .field("table-hash", &self.table_hash)
                            .field("payload", &self.payload)
                            .field("ts-ns", &self.ts_ns)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct QdrantUpsert {
                    pub collection: _rt::String,
                    pub point_id: _rt::String,
                    pub vector: _rt::Vec<f32>,
                    pub payload_json: _rt::String,
                    pub tenant_id: u64,
                }
                impl ::core::fmt::Debug for QdrantUpsert {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("QdrantUpsert")
                            .field("collection", &self.collection)
                            .field("point-id", &self.point_id)
                            .field("vector", &self.vector)
                            .field("payload-json", &self.payload_json)
                            .field("tenant-id", &self.tenant_id)
                            .finish()
                    }
                }
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct DeltaStats {
                    pub cosine_distance: f32,
                    pub skipped: bool,
                    pub tokens_processed: u32,
                }
                impl ::core::fmt::Debug for DeltaStats {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("DeltaStats")
                            .field("cosine-distance", &self.cosine_distance)
                            .field("skipped", &self.skipped)
                            .field("tokens-processed", &self.tokens_processed)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_process_cabi<T: Guest>(
                    arg0: i64,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: *mut u8,
                    arg4: usize,
                    arg5: i64,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let len1 = arg4;
                    let result2 = T::process(CdcEvent {
                        tenant_id: arg0 as u64,
                        table_hash: _rt::Vec::from_raw_parts(arg1.cast(), len0, len0),
                        payload: _rt::Vec::from_raw_parts(arg3.cast(), len1, len1),
                        ts_ns: arg5 as u64,
                    });
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let (t4_0, t4_1) = e;
                            match t4_0 {
                                Some(e) => {
                                    *ptr3.add(8).cast::<u8>() = (1i32) as u8;
                                    let QdrantUpsert {
                                        collection: collection5,
                                        point_id: point_id5,
                                        vector: vector5,
                                        payload_json: payload_json5,
                                        tenant_id: tenant_id5,
                                    } = e;
                                    let vec6 = (collection5.into_bytes()).into_boxed_slice();
                                    let ptr6 = vec6.as_ptr().cast::<u8>();
                                    let len6 = vec6.len();
                                    ::core::mem::forget(vec6);
                                    *ptr3
                                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len6;
                                    *ptr3.add(16).cast::<*mut u8>() = ptr6.cast_mut();
                                    let vec7 = (point_id5.into_bytes()).into_boxed_slice();
                                    let ptr7 = vec7.as_ptr().cast::<u8>();
                                    let len7 = vec7.len();
                                    ::core::mem::forget(vec7);
                                    *ptr3
                                        .add(16 + 3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len7;
                                    *ptr3
                                        .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr7.cast_mut();
                                    let vec8 = (vector5).into_boxed_slice();
                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                    let len8 = vec8.len();
                                    ::core::mem::forget(vec8);
                                    *ptr3
                                        .add(16 + 5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len8;
                                    *ptr3
                                        .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr8.cast_mut();
                                    let vec9 = (payload_json5.into_bytes()).into_boxed_slice();
                                    let ptr9 = vec9.as_ptr().cast::<u8>();
                                    let len9 = vec9.len();
                                    ::core::mem::forget(vec9);
                                    *ptr3
                                        .add(16 + 7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len9;
                                    *ptr3
                                        .add(16 + 6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr9.cast_mut();
                                    *ptr3
                                        .add(16 + 8 * ::core::mem::size_of::<*const u8>())
                                        .cast::<i64>() = _rt::as_i64(tenant_id5);
                                }
                                None => {
                                    *ptr3.add(8).cast::<u8>() = (0i32) as u8;
                                }
                            };
                            let DeltaStats {
                                cosine_distance: cosine_distance10,
                                skipped: skipped10,
                                tokens_processed: tokens_processed10,
                            } = t4_1;
                            *ptr3
                                .add(24 + 8 * ::core::mem::size_of::<*const u8>())
                                .cast::<f32>() = _rt::as_f32(cosine_distance10);
                            *ptr3
                                .add(28 + 8 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match skipped10 {
                                true => 1,
                                false => 0,
                            }) as u8;
                            *ptr3
                                .add(32 + 8 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(tokens_processed10);
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec11 = (e.into_bytes()).into_boxed_slice();
                            let ptr11 = vec11.as_ptr().cast::<u8>();
                            let len11 = vec11.len();
                            ::core::mem::forget(vec11);
                            *ptr3
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len11;
                            *ptr3.add(8).cast::<*mut u8>() = ptr11.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_process<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = i32::from(*arg0.add(8).cast::<u8>());
                            match l1 {
                                0 => {}
                                _ => {
                                    let l2 = *arg0.add(16).cast::<*mut u8>();
                                    let l3 = *arg0
                                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l2, l3, 1);
                                    let l4 = *arg0
                                        .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l5 = *arg0
                                        .add(16 + 3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l4, l5, 1);
                                    let l6 = *arg0
                                        .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l7 = *arg0
                                        .add(16 + 5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let base8 = l6;
                                    let len8 = l7;
                                    _rt::cabi_dealloc(base8, len8 * 4, 4);
                                    let l9 = *arg0
                                        .add(16 + 6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l10 = *arg0
                                        .add(16 + 7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l9, l10, 1);
                                }
                            }
                        }
                        _ => {
                            let l11 = *arg0.add(8).cast::<*mut u8>();
                            let l12 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l11, l12, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_flush_batch_cabi<T: Guest>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::flush_batch();
                    _rt::as_i32(result0)
                }
                pub trait Guest {
                    fn process(
                        event: CdcEvent,
                    ) -> Result<(Option<QdrantUpsert>, DeltaStats), _rt::String>;
                    fn flush_batch() -> u32;
                }
                #[doc(hidden)]
                macro_rules! __export_nexuscore_cdc_processor_0_3_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "nexuscore:cdc/processor@0.3.0#process")] unsafe extern "C" fn
                        export_process(arg0 : i64, arg1 : * mut u8, arg2 : usize, arg3 :
                        * mut u8, arg4 : usize, arg5 : i64,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_process_cabi::<$ty > (arg0, arg1,
                        arg2, arg3, arg4, arg5) } } #[unsafe (export_name =
                        "cabi_post_nexuscore:cdc/processor@0.3.0#process")] unsafe extern
                        "C" fn _post_return_process(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_process::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "nexuscore:cdc/processor@0.3.0#flush-batch")] unsafe extern "C"
                        fn export_flush_batch() -> i32 { unsafe { $($path_to_types)*::
                        _export_flush_batch_cabi::<$ty > () } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_nexuscore_cdc_processor_0_3_0_cabi;
                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 40 + 8 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 40
                        + 8 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_f32<T: AsF32>(t: T) -> f32 {
        t.as_f32()
    }
    pub trait AsF32 {
        fn as_f32(self) -> f32;
    }
    impl<'a, T: Copy + AsF32> AsF32 for &'a T {
        fn as_f32(self) -> f32 {
            (*self).as_f32()
        }
    }
    impl AsF32 for f32 {
        #[inline]
        fn as_f32(self) -> f32 {
            self as f32
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_cdc_processor_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::nexuscore::cdc::processor::__export_nexuscore_cdc_processor_0_3_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::nexuscore::cdc::processor);
    };
}
#[doc(inline)]
pub(crate) use __export_cdc_processor_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:nexuscore:cdc@0.3.0:cdc-processor:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 476] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd8\x02\x01A\x02\x01\
A\x02\x01B\x0f\x01p}\x01r\x04\x09tenant-idw\x0atable-hash\0\x07payload\0\x05ts-n\
sw\x04\0\x09cdc-event\x03\0\x01\x01pv\x01r\x05\x0acollections\x08point-ids\x06ve\
ctor\x03\x0cpayload-jsons\x09tenant-idw\x04\0\x0dqdrant-upsert\x03\0\x04\x01r\x03\
\x0fcosine-distancev\x07skipped\x7f\x10tokens-processedy\x04\0\x0bdelta-stats\x03\
\0\x06\x01k\x05\x01o\x02\x08\x07\x01j\x01\x09\x01s\x01@\x01\x05event\x02\0\x0a\x04\
\0\x07process\x01\x0b\x01@\0\0y\x04\0\x0bflush-batch\x01\x0c\x04\0\x1dnexuscore:\
cdc/processor@0.3.0\x05\0\x04\0!nexuscore:cdc/cdc-processor@0.3.0\x04\0\x0b\x13\x01\
\0\x0dcdc-processor\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-compo\
nent\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
